FROM node:16-bullseye as base

WORKDIR /app/backend
COPY package*.json yarn.lock ./

RUN yarn --frozen-lockfile --no-cache

FROM base as builder
COPY . .
RUN yarn build

FROM base as runtime

ENV NODE_ENV=production

RUN yarn --frozen-lockfile --no-cache --production

COPY --from=builder ./dist ./dist
COPY --from=builder ./build ./build

EXPOSE 3001

CMD ["node", "dist/server.js"]
