# dockerfile build for astro using node 18
FROM node:18-alpine as runtime

WORKDIR /home/node
COPY . .

RUN npm i -g pnpm@latest

RUN pnpm i
RUN pnpm build

EXPOSE 4000
CMD PORT=4000 node ./dist/server/entry.mjs
