version: '3'

services:
  payload:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.dev
    ports:
      - '3001:3001'
    volumes:
      - .:/home/node/app
      - node_modules:/home/node/app/node_modules
    depends_on:
      - mongo
    env_file:
      - .env.development

  mongo:
    image: mongo:latest
    ports:
      - '27017:27017'
    command:
      - --storageEngine=wiredTiger
    volumes:
      - data:/data/db
    logging:
      driver: none

volumes:
  data:
  node_modules:
