FROM node:16-bullseye as base

FROM base as builder

WORKDIR /home/node
COPY package*.json yarn.lock ./

COPY . .
# Clear yarn cache
RUN yarn cache clean && \
  rm -rf /tmp/*
RUN yarn
RUN yarn build

FROM base as runtime

ENV NODE_ENV=production

WORKDIR /home/node
COPY package*.json yarn.lock ./

RUN yarn
COPY --from=builder /home/node/dist ./dist
COPY --from=builder /home/node/build ./build

EXPOSE 3001

CMD ["node", "dist/server.js"]
